# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[pt-br]
  languageCode = "pt-br"
  contentDir = "content/pt-br"
  title = "Germano Bortolotto"
  [[pt-br.main]]
    name = "Sobre"
    url = "sobre"
    weight = 10
  [[pt-br.main]]
    name = "Blog"
    url = "post"
    weight = 20
  [[pt-br.main]]
    name = "Publicações"
    url = "publicacoes"
    weight = 30
  [[pt-br.main]]
    name = "Projetos"
    url = "projetos"
    weight = 40
#  [zh.params]
#    description = "Site description in Chinese..."
#  [[zh.menu.main]]
#    name = "Wo"
#    url = "#about"
#    weight = 1

