---
title: "Alan Turing"
author: Germano Bortolotto
date: '2020-06-28'
slug: alan-turing
categories:
  - lgbt
tags:
  - lgbt
  - turing
  - pride
subtitle: ''
summary: "Some words on Pride Day. An example of importance and influence of LGBT people in our history"
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: true
projects: []
---


Today, June 28, is internationally known as Pride Day. This date was chosen as a reference to the [Stonewall Inn riots](https://en.wikipedia.org/wiki/Stonewall_riots), an episode remembered as a milestone in gay activism.  Since that day, much progress has been done towards acceptance and inclusion of LGBTQIA+ people in many places around the world. In this post I want to highlight some contributions made by these people that allowed to world to become what it is today. 

During my academic and professional life, few names were more cited than that of Alan Turing, the British mathematician known as "the father of modern computing".

Born in June 23, 1912, Turing developed some thoughts on the similarities between a brain and a computer, establishing the idea of the brain as a "computing machine". 

One concept that is becoming mainstream in the era of Artificial Intelligente (AI) is that of a "thinking machine". In his 1950 paper, ["Computing machinery and intelligence"](https://academic.oup.com/mind/article/LIX/236/433/986238), Turing proposes that if a computer can provide answers in a way indistinguishable from how a human would perform in natural language conversation, than one could argue the this computes shows a kind of intelligent behavior. In his paper he uses the Imitation Game as starting point to his arguments. Interestingly, the movie ["The Imitation game"](https://www.imdb.com/title/tt2084970/) (2014), an historical drama based on Turing's life, barely mentions this idea, which is much better exploited in the movie ["Ex-Machina"](https://www.imdb.com/title/tt0470752/) released the following year.

Besides his work on computational science, Turing is also credited for having decoded Enigma's criptography. Enigma was a a machine used by the Nazis during the Second World War do send coded messages. Once the code was broken, the Allies could anticipate Axis' moves and act accordingly. This episode is considered one of the war's turning points.

However, all his contributions were not enough to save his life. Turing was homosexual, and on 1952 he was prosecuted for "gross indecency". He had two options: 1. prison; 2. chemical castration. He chose the latter. He was found dead on 1954, victim cyanide poisoning. However, there are some divergences whether it was suicide or accidental poisoning.

It took almot 60 years to his condenation to be revisited. In 2013, Queen Elizabeth II granted Turing [a posthumous pardon](https://www.bbc.com/news/technology-25495315). It is said that his face will be printed on the £50 note as a recognition for [his lifetime works](https://www.theguardian.com/science/2019/jul/15/alan-turing-father-of-modern-computing-50-pound-note).

Alan Turing's life and influence in the past 50 years can be taken as an example of the presence and importance of LGBTQIA+ people in the world. Science and culture would not be so advanced or diverse or powerful if not by their work. 

Although much as been done in the past years to ensure basic human rights, there is still so much to fight for. Let's take this day as a celebration of our conquests and a reminder of the lives, sufferings and contributions of the ones that came before. May the Alan Turing's of today and the future be able to live as they want, be who they are, and contribute to humanity's growth, no matter their desires and aptitudes.  


## References 

1. [Stonewall Riots - Wikipedia](https://en.wikipedia.org/wiki/Stonewall_riots)
2. Turing, Alan (1950), **Computing Machinery and Intelligence**, Mind, LIX (236): 433–460. [(link)](https://academic.oup.com/mind/article/LIX/236/433/986238)
3. [The Imitation Game (IMDb)](https://www.imdb.com/title/tt2084970/)
4. [Ex-Machina (IMDb)](https://www.imdb.com/title/tt0470752/)
5. [Royal pardon for codebreaker Alan Turing - BBC](https://www.bbc.com/news/technology-25495315)
6. [Turing's face on the pound note - The Guardian](https://www.theguardian.com/science/2019/jul/15/alan-turing-father-of-modern-computing-50-pound-note)
