---
title: "Why I decided to leave a management position"
author: Germano Bortolotto
date: '2022-02-22'
slug: leave-management-position
categories:
  - management
  - job
tags:
  - management
  - job
  - career
subtitle: ''
summary: "When you start getting there but something is missing"
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: true
projects: []
---
    
By the end of 2017 it was obvious to me that I wasn’t happy pursuing an academic career. Even though I loved doing research, writing code and working on my own pace and projects, the lack of urgency, small number of collaborators and people who would actually benefit from all those work hours were downsides for me.

One solution was to work outside the University. I've never done this other than some temporary extension projects. As I had some experience using machine learning methods and I knew how to code [sort of] I applied to some local companies in order to see what were people doing those days.

After a couple of months I finally landed a job as a data scientist in a major Brazilian call center. I did all kinds of analysis, profile segmentation and contact optimization. It was a new challenge everyday and that was amazing. 

By the end of that year a former colleague of mine invited me to help build a new company, an startup focused on outsourcing analysis to big players in the market. There I was able to work with almost everything. I spent a lot of time creating ML models and power visualizations, but I was also required to develop transformation pipelines, work with kubernetes clusters, build and deploy different databases, act as scrum master and product manager, hire new people and deal with some of the company finances. There wasn't a single day when I wasn't studying something new. I was challenged to understand and apply new technologies on a daily basis. It felt like doing research at 4x speed. 

With all that fast acquired experience I accepted a new job offer in a bigger company, where I worked as a full time data engineer. There I learned to work with different teams, different softwares and a whole new knowledge field for me: sales. 

After a series of events, and given my past involvement in team management activities, I was promoted to “data engineering manager”. So there I was, climbing on the corporate ladder, faster than I ever envisioned, becoming more distant from the academic world with each day. It was actually a nice period in my life. I participated in important meetings and had an active voice in shaping part of the company's future: what problems to address, which software and equipment to use, who to hire, but something was still missing.

It was great to receive that kind of recognition, but I was missing… the thrill, the discovery. After only 3 years I went from a PhD student in neuroscience, working mostly alone in a promising field but with few resources and collaborators, to a management position in a medium sized company, leading a team and creating new products. However, each day seemed more of the same. Lots of meetings and feedbacks but few lines of code. When a new job offer came, with the opportunity to work in a bigger team, being able to learn new technologies and software, create new stuff and still being paid for that, I didn’t think twice. In the end, that’s what I always wanted to do, even before going to physics school: discover something every day and have the concrete feeling that my daily routine would positively impact my life, my job and the world we live in.

I don’t consider this move as a “step back”. It is a realization of my objectives and a way to fulfill what brings joy to my life. Don’t be too eager to get those promotions and become that high profile corporate title: maybe you will realize that you will prefer the path to it.

That was my story on why I decided to leave a management position and go back to getting my hands dirty with all that technical stuff. For more on that, please follow [my twitter account](https://twitter.com/gerbortolotto).